elfin:
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 1000
    
    cloned_clik_controller_1:
      type: arm_controllers/Cloned_CLIK_controller_1
      joints:
        - elfin_joint1
        - elfin_joint2
        - elfin_joint3
        - elfin_joint4
        - elfin_joint5
        - elfin_joint6
        
      gains:
        elfin_joint1: 
          pid: {p: 10000.0, i: 0, d: 500.0}
        elfin_joint2: 
          pid: {p: 10000.0, i: 0, d: 500.0}
        elfin_joint3: 
          pid: {p: 10000.0, i: 0, d: 500.0}
        elfin_joint4: 
          pid: {p: 10000.0, i: 0, d: 500.0}
        elfin_joint5: 
          pid: {p: 10000.0, i: 0, d: 500.0}
        elfin_joint6: 
          pid: {p: 10000.0, i: 0, d: 500.0}

      root_link: world
      tip_link: elfin_link6

      ctr_obj: 1  # ctr_obj = 1: Regulation 
                  # ctr_obj = 2: Tracking
                  
      ik_mode: 2 # open-loop inverse kinematics using jacobian
                 # closed-loop inverse Kinematics using jacobian

      clik_gain: {K_regulation: 6.0, K_tracking: 3.0}

    cloned_clik_controller_2:
      type: arm_controllers/Cloned_CLIK_controller_2
      joints:
        - elfin_joint1
        - elfin_joint2
        - elfin_joint3
        - elfin_joint4
        - elfin_joint5
        - elfin_joint6
        
      gains:
        elfin_joint1: 
          pid: {p: 10000.0, i: 0, d: 500.0}
        elfin_joint2: 
          pid: {p: 10000.0, i: 0, d: 500.0}
        elfin_joint3: 
          pid: {p: 10000.0, i: 0, d: 500.0}
        elfin_joint4: 
          pid: {p: 10000.0, i: 0, d: 500.0}
        elfin_joint5: 
          pid: {p: 10000.0, i: 0, d: 500.0}
        elfin_joint6: 
          pid: {p: 10000.0, i: 0, d: 500.0}

      root_link: world
      tip_link: elfin_link6

      ctr_obj: 1  # ctr_obj = 1: Regulation 
                  # ctr_obj = 2: Tracking
                  
      ik_mode: 2 # open-loop inverse kinematics using jacobian
                 # closed-loop inverse Kinematics using jacobian

      clik_gain: {K_regulation: 6.0, K_tracking: 3.0}
      
            
    cloned_gravity:
      type: arm_controllers/Cloned_Gravity
      joints:
        - elfin_joint1
        - elfin_joint2
        - elfin_joint3
        - elfin_joint4
        - elfin_joint5
        - elfin_joint6
      gains:
        elfin_joint1:
          pid: {p: 200.0, i: 10, d: 10.0, i_clamp: 50, antiwindup: true}
        elfin_joint2: 
          pid: {p: 100, i: 5, d: 20, i_clamp: 50, antiwindup: true}
        elfin_joint3:
          pid: {p: 200.0, i: 10, d: 0.0, i_clamp: 50, antiwindup: true}
        elfin_joint4: 
          pid: {p: 200.0, i: 10, d: 0.0, i_clamp: 50, antiwindup: true}
        elfin_joint5: 
          pid: {p: 200.0, i: 10, d: 5.0, i_clamp: 50, antiwindup: true}
        elfin_joint6: 
          pid: {p: 200.0, i: 5, d: 5.0, i_clamp: 50, antiwindup: true}
      root_link: world
      tip_link: elfin_link6
